apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: webfilter-report
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05"
      timezone: "Local"
  artifacts:
  - image: bang5:5000/webfilter_report_image
    sync:
      infer:
        - frontend/index.html
        - frontend/build/bundle.js
deploy:
  kubectl:
    manifests:
    - deploy.yaml
