apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-route-input
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-route-input
  template:
    metadata:
      labels:
        app: net-route-input
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: net-route-input
          image: bang5:5000/net_route_input_image
          ports:
            - containerPort: 8000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values: ["bang"]
---
apiVersion: v1
kind: Service
metadata:
  name: net-route-input
spec:
  ports:
    - { port: 80, targetPort: 8000, name: http }
  selector:
    app: net-route-input
