apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-routes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-routes
  template:
    metadata:
      labels:
        app: net-routes
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 1
      containers:
        - name: net-routes
          image: bang5:5000/net_routes_image
          securityContext: { capabilities: { add: [NET_ADMIN, NET_RAW] } }
          ports:
            - containerPort: 10001
          volumeMounts:
            - { name: host-run, mountPath: /run } # for /run/xtables.lock
      volumes:
        - { name: host-run, hostPath: { path: /run } }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values: ["bang"]
---
apiVersion: v1
kind: Service
metadata:
  name: net-routes
spec:
  ports:
    - { port: 80, targetPort: 10001, name: http }
  selector:
    app: net-routes
